spring.datasource.url=jdbc:postgresql://postgres:5432/onlinestore
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.generate-ddl=true
spring.liquibase.change-log=classpath:/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
server.port=9090
jwt.token.secret=jwtonlinestore
jwt.token.expired=3600000
